from __future__ import annotations

BASE_STYLE = """
<style>
.mw-print { font-family: Arial, sans-serif; font-size: 10pt; color: #111; }
.mw-print h1 { font-size: 18pt; margin: 0 0 8px; }
.mw-print h2 { font-size: 12pt; margin: 16px 0 6px; border-bottom: 1px solid #bbb; }
.mw-grid { width: 100%; border-collapse: collapse; }
.mw-grid th, .mw-grid td { border: 1px solid #bbb; padding: 5px; vertical-align: top; }
.mw-grid th { background: #f3f3f3; text-align: left; }
.mw-right { text-align: right; }
.mw-muted { color: #555; }
</style>
"""

PRINT_FORMATS = {
	"Malaysia Payslip": {
		"doctype": "Salary Slip",
		"html": BASE_STYLE + """
<div class=\"mw-print\">
<h1>Payslip / Penyata Gaji</h1>
<table class=\"mw-grid\"><tr><th>Employee</th><td>{{ doc.employee_name }} ({{ doc.employee }})</td><th>Period</th><td>{{ frappe.utils.formatdate(doc.start_date) }} – {{ frappe.utils.formatdate(doc.end_date) }}</td></tr><tr><th>Company</th><td>{{ doc.company }}</td><th>Net Pay</th><td class=\"mw-right\">{{ frappe.utils.fmt_money(doc.net_pay, currency=doc.currency) }}</td></tr></table>
<h2>Earnings</h2><table class=\"mw-grid\"><tr><th>Component</th><th class=\"mw-right\">Amount</th></tr>{% for row in doc.earnings %}<tr><td>{{ row.salary_component }}</td><td class=\"mw-right\">{{ frappe.utils.fmt_money(row.amount, currency=doc.currency) }}</td></tr>{% endfor %}</table>
<h2>Deductions</h2><table class=\"mw-grid\"><tr><th>Component</th><th class=\"mw-right\">Amount</th></tr>{% for row in doc.deductions %}<tr><td>{{ row.salary_component }}</td><td class=\"mw-right\">{{ frappe.utils.fmt_money(row.amount, currency=doc.currency) }}</td></tr>{% endfor %}</table>
{% if doc.custom_malaysia_statutory_results %}<h2>Statutory Contributions</h2><table class=\"mw-grid\"><tr><th>Scheme</th><th>Wage Base</th><th>Employee</th><th>Employer</th></tr>{% for row in doc.custom_malaysia_statutory_results %}<tr><td>{{ row.scheme }}</td><td class=\"mw-right\">{{ frappe.utils.fmt_money(row.wage_base, currency=doc.currency) }}</td><td class=\"mw-right\">{{ frappe.utils.fmt_money(row.employee_amount + row.extra_employee_amount, currency=doc.currency) }}</td><td class=\"mw-right\">{{ frappe.utils.fmt_money(row.employer_amount, currency=doc.currency) }}</td></tr>{% endfor %}</table>{% endif %}
<p class=\"mw-muted\">Generated by ERPNext Malaysia Workforce.</p></div>
""",
	},
	"Malaysia TP1 2026": {
		"doctype": "Malaysia Tax Declaration TP1",
		"html": BASE_STYLE + """<div class=\"mw-print\"><h1>Form TP1 / Borang TP1</h1><p>Year: {{ doc.tax_year }} &nbsp; Employee: {{ doc.employee }}</p><table class=\"mw-grid\"><tr><th>Relief</th><th>Description</th><th>Amount (RM)</th></tr>{% for row in doc.relief_claims %}<tr><td>{{ row.relief_code }}</td><td>{{ row.description }}</td><td class=\"mw-right\">{{ '%.2f'|format(row.amount) }}</td></tr>{% endfor %}<tr><th colspan=\"2\">Total</th><th class=\"mw-right\">{{ '%.2f'|format(doc.total_reliefs) }}</th></tr></table><p>I declare that the information provided is true and complete.</p></div>""",
	},
	"Malaysia TP3 2026": {
		"doctype": "Malaysia Previous Employment TP3",
		"html": BASE_STYLE + """<div class=\"mw-print\"><h1>Form TP3 / Borang TP3</h1><p>Employee: {{ doc.employee }} &nbsp; Tax year: {{ doc.tax_year }}</p><table class=\"mw-grid\"><tr><th>Previous employer</th><td>{{ doc.previous_employer_name }}</td></tr><tr><th>Gross remuneration</th><td>{{ '%.2f'|format(doc.gross_normal_remuneration + doc.gross_additional_remuneration) }}</td></tr><tr><th>EPF</th><td>{{ '%.2f'|format(doc.epf_contribution) }}</td></tr><tr><th>MTD</th><td>{{ '%.2f'|format(doc.mtd_paid) }}</td></tr><tr><th>Zakat</th><td>{{ '%.2f'|format(doc.zakat_paid) }}</td></tr></table></div>""",
	},
	"Malaysia Employee Notification": {
		"doctype": "Malaysia Employee Notification",
		"html": BASE_STYLE + """<div class=\"mw-print\"><h1>{{ doc.form_type }}</h1><table class=\"mw-grid\"><tr><th>Employee</th><td>{{ doc.employee }}</td><th>Company</th><td>{{ doc.company }}</td></tr><tr><th>Trigger date</th><td>{{ frappe.utils.formatdate(doc.trigger_date) }}</td><th>Due date</th><td>{{ frappe.utils.formatdate(doc.due_date) if doc.due_date else '' }}</td></tr><tr><th>Reason</th><td colspan=\"3\">{{ doc.reason or '' }}</td></tr></table><p class=\"mw-muted\">This is an ERP preparation worksheet. Submit using the current official LHDN e-service and retain the official acknowledgement.</p></div>""",
	},
	"Malaysia EA EC Statement": {
		"doctype": "Malaysia Annual Remuneration Statement",
		"html": BASE_STYLE + """<div class=\"mw-print\"><h1>{{ doc.form_type }} – Year {{ doc.tax_year }}</h1><p>Employee: {{ doc.employee }} &nbsp; Company: {{ doc.company }}</p><table class=\"mw-grid\"><tr><th>Gross remuneration</th><td class=\"mw-right\">{{ '%.2f'|format(doc.gross_remuneration) }}</td></tr><tr><th>Benefits in kind</th><td class=\"mw-right\">{{ '%.2f'|format(doc.benefits_in_kind) }}</td></tr><tr><th>EPF employee</th><td class=\"mw-right\">{{ '%.2f'|format(doc.epf_employee) }}</td></tr><tr><th>SOCSO employee</th><td class=\"mw-right\">{{ '%.2f'|format(doc.socso_employee) }}</td></tr><tr><th>EIS employee</th><td class=\"mw-right\">{{ '%.2f'|format(doc.eis_employee) }}</td></tr><tr><th>PCB</th><td class=\"mw-right\">{{ '%.2f'|format(doc.pcb) }}</td></tr><tr><th>CP38</th><td class=\"mw-right\">{{ '%.2f'|format(doc.cp38) }}</td></tr></table></div>""",
	},
}
